#!/usr/bin/env bash
# What happens when you type `google.com` in your browser and press Enter
https://medium.com/@tmuli974/what-happens-when-you-type-google-com-in-your-browser-and-press-enter-2aac6727881d
