#!/usr/bin/env bash
# install nginx on your web server

sudo apt -y update
sudo apt -y upgrade
sudo apt-get install -y nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo chown -R ubuntu:ubuntu /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/nullsudo service nginx start
