#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument.

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip=$1

echo "Pinging $ip..."

for i in {1..5}; do
  ping -c1 $ip > /dev/null && echo "$ip is up" || echo "$ip is down"
done
