#!/usr/bin/env bash
# what’s keeping your Ubuntu container’s Nginx installation from listening on port 8?
# configures nginx to run and listen to port 80

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
