#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker

cp /etc/hosts ~/hosts.new
sed -i '/^127.0.0.1.*localhost/ s/^127.0.0.1.*/127.0.0.2 localhost/' ~/hosts.new
sed -i '/^.*facebook.com/ s/^.*facebook.com/8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
