#!/usr/bin/env bash
#it shows all ip addresses

ips = $(ifconfig | grep 'inet' | awk '{print $2}')

for ip in $ips
do
    if [[ $ip == *"127.0.0.1"* || $ip*":"* ]]; then
        continue
    else
        echo "$ip"
    fi
done