#!/usr/bin/env bash
# Client configuration file

CONFIG_FILE=~/.ssh/config

if [ !-f "$CONFIG_FILE" ]; then
    touch "$CONFIG_FILE"
fi

echo "Host your-server" >> "$CONFIG_FILE"
echo "HostName your-server-ip" >> "$CONFIG_FILE"
echo "User ubuntu" >> "$CONFIG_FILE"
echo "IdentityFile ~/.ssh/school" >> "$CONFIG_FILE"
echo "PreferredAuthentications publickey" >> "$CONFIG_FILE"
echo "PasswordAuthentication no" >> "$CONFIG_FILE"

echo "SSH client configuration updated successfully."
